### ISSUE TITLE
scrambled omk icon?

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/OpenMapKitWebsite#6]
doesn't look like logo is displaying correctly on the landing page

![screen shot 2015-12-18 at 8 41 23 am](https://cloud.githubusercontent.com/assets/4806884/11898118/853838c4-a563-11e5-8525-8d765d243771.png)

**Comment by dalekunce** [comment]
I think a clipping mask is missing.

**Comment by danielduhh** [comment]
working on getting a new svg from naomi

**Comment by dalekunce** [comment]
This is still showing up.

![screen shot 2016-02-05 at 3 15 15 pm](https://cloud.githubusercontent.com/assets/1913857/12857997/5d316c2c-cc1b-11e5-9930-c9b753c8d6c4.png)

**Comment by lancesnider** [comment]
Here's an .SVG and .AI file for just the Open OMK App icon. Someone will still have to add this to the font. I basically just got rid of the masking because that can have some pretty funky results in browser. 
<img width="510" alt="screen shot 2016-06-10 at 4 39 14 pm" src="https://cloud.githubusercontent.com/assets/3202211/15980562/e603b106-2f29-11e6-9489-6f588072e852.png">
[icn-logo_OMK.zip](https://github.com/AmericanRedCross/OpenMapKitWebsite/files/309926/icn-logo_OMK.zip)

**Comment by danbjoseph** [comment]
@jharpster can we get the single SVG's for the other icons in the font so we can update it 

https://github.com/AmericanRedCross/OpenMapKitWebsite/blob/master/css/fonts.css
it looks like there are six others?

**Comment by jharpster** [comment]
Passing the torch on this one to @danielduhh who can chase it down internally.

**Comment by danielduhh** [comment]
@danbjoseph 
[omkWebsiteIcons.zip](https://github.com/AmericanRedCross/OpenMapKitWebsite/files/364737/omkWebsiteIcons.zip)

**Comment by danbjoseph** [comment]
thanks!

**Comment by danbjoseph** [comment]
this is fixed now.
