### ISSUE TITLE
POSM vs. OMK Server

### ISSUE THREAD

**Issue by dalekunce** [AmericanRedCross/OpenMapKitWebsite#9]
We need a simple provisioning workflow for OMK. Can this be handled by posm-depoly

**Comment by hallahan** [comment]
Yes, posm-deploy is deploying OpenMapKit Server.

**Comment by hallahan** [comment]
Sorry, I misunderstood your question.

I think we should have posm-deployment primarily be a NodeJS job queue service reading deployment manifest files and fire up jobs. We might want to move your react app to a public subdirectory in the project or somewhere else.

**Comment by mojodna** [comment]
Let's consider @dalekunce's React app as a placeholder for a modified HOT Export Tool instance unless we decide otherwise.

We still need the provisioning workflow for OMK somewhere. A HOT Export Tool task might suffice, but I don't have enough info.

Can someone close this in favor of https://github.com/AmericanRedCross/posm/issues/26?

**Comment by jharpster** [comment]
We're looking at this a little more closely as well. Lets settle on a game plan when we meet at the end of this week.
